name: bmtc_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  google_fonts: ^6.3.2
  get: ^4.7.2
  pin_code_fields: ^8.0.1
  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.12.0
  video_player: ^2.10.1
  cached_video_player_plus: ^4.0.4
  youtube_player_flutter: ^9.1.3
  file_picker: ^10.3.7
  table_calendar: ^3.2.0
  image_picker: ^1.2.1
  internet_connection_checker: ^3.0.1
  connectivity_plus: ^6.1.5
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/app-logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo/app-logo.png"

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#FFFFFF"
  image: "assets/logo/app-logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
    - assets/icons/
